export * from "./HomePage";
export * from "./RegisterPage";
export * from "./LoginPage";
export * from "./MainPage";
export * from "./CoursesPage";
export * from "./CurrentCoursePage";
export * from "./ProfilePage";
export * from "./StudentLandingPage";
export * from "./StudentCoursePage";
